// Story-beat skeleton per zone (content/map/story-beats.json, generated by
// scripts/build/build-story-beats.py from the internal guidebook adaptation).
// Internal working data in French — never render its text in the product
// (PRD § Langue du Jeu); the map only surfaces counts/markers from it.

interface StoryBeatZone {
  display_name: string
  order: number
  beats: { type: string; text: string }[]
  locks: string[]
}

// eslint-disable-next-line @typescript-eslint/no-require-imports
const raw = require('../../content/map/story-beats.json') as { zones: Record<string, StoryBeatZone> }

const knownZoneIds = Object.keys(raw.zones)

function normalizeMapName(mapName: string): string {
  return mapName.replace(/^MAP_/, '').toLowerCase().replace(/_/g, '-')
}

// Same matching as src/lib/npcs.ts: story-beat zone_ids are human slugs
// ("new-bark-town"), registry names are ROM map names ("MAP_NEW_BARK").
function zoneIdForMapName(mapName: string): string | undefined {
  const normalized = normalizeMapName(mapName)
  return knownZoneIds.find(zoneId => zoneId === normalized || zoneId.startsWith(`${normalized}-`))
}

/** Number of story beats anchored in the zone a MAP_* name belongs to —
 * 0 when the zone has none (or isn't covered by the guidebook adaptation). */
export function beatCountForMapName(mapName: string): number {
  const zoneId = zoneIdForMapName(mapName)
  return zoneId ? raw.zones[zoneId].beats.length : 0
}
